### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by akshayc11**

### CODE REVIEW

**Comment by davidogbodfog** [comment]
It's cool. When I zoom in, I expect the circles to get larger.

**Comment by davidogbodfog** [comment]
Also, the map snaps to specific Zoom levels instead of just staying at the same level that you zoom in to. At least this is the case when I use it on my tablet. Also, even though it restricts you from creating dots outside the polygon, it allows you to drag the dots outside the polygon once they have been created.

**Comment by davidogbodfog** [comment]
Ok, it looks like the Zoom snapping issue happens on all maps, not just this one.

**Comment by akshayc11** [comment]
I see.. let me see what needs to be done for the dragging out case...

**Pull request closed without merging**
